name: 1 - ğŸ‘Œ test mock back

on:
  push:
    branches: ['1-mock-livres']

jobs:
  test:
    name: ğŸ”¦ Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‰ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸˆ Install dependencies
        run: |
          cd backend
          npm install
